# ~/.tmux.conf

set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_date_time_text " %y-%m-%d %H:%M"
set -gF  status-right "#{@catppuccin_status_directory}"
set -agF status-right "#{@catppuccin_status_session}"
set -agF status-right "#{@catppuccin_status_user}"
set -agF status-right "#{@catppuccin_status_host}"
set -agF status-right "#{@catppuccin_status_date_time}"

bind r source-file ~/.tmux.conf

bind \\ split-window -h
bind - split-window -v

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D
